run_id: "acl_generalist_8h_run"

total_stages: 10
student_steps_per_stage: 100000 

eval_episodes: 10
mastery_threshold: 50.0 
n_envs: 8
seed: 42

difficulty_dims:
  - input_vector_0
  - input_vector_1
  - water_level
  - creepers_height
  - creepers_spacing

initial_difficulty: [0.0, 0.0, 0.0, 0.0, 1.0]

mastery_order:
  - input_vector_0
  - input_vector_1
  - water_level
  - creepers_height
  - creepers_spacing

difficulty_increments:
  input_vector_0: 0.2
  input_vector_1: 0.2
  water_level: 0.1
  creepers_height: 0.2
  creepers_spacing: -0.1 # Giảm khoảng cách để làm khó hơn

ppo_config:
  learning_rate: 0.0003
  buffer_size: 500000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  learning_starts: 10000